// Generated by tinympc
#pragma once

#include <tinympc/types.hpp>

namespace mpc_config {

constexpr int MODEL_SIMPLE = 0;
constexpr int MODEL_SINGLE_STANDARD = 1;
constexpr int MODEL_KIND = 1;
constexpr int NX = 4;
constexpr int NU = 1;
constexpr int HORIZON = 30;
constexpr tinytype DT = 0.02;
constexpr unsigned long DT_US = 20000UL;
constexpr int BENCHMARK_STEPS = 50;
constexpr tinytype REFERENCE_PERIOD = 5;
constexpr tinytype REFERENCE_AMPLITUDE_X = 0.14999999999999999;
constexpr tinytype REFERENCE_AMPLITUDE_Y = 0;
constexpr tinytype REFERENCE_START_SIGN = 1;
constexpr tinytype GRAVITY_TORQUE_GAIN = 0.088290000000000021;
constexpr tinytype PENDULUM_INERTIA = 0.00086249999999999999;
constexpr tinytype RHO = 0.29999999999999999;
constexpr tinytype ABS_PRI_TOL = 0.01;
constexpr tinytype ABS_DUA_TOL = 0.01;
constexpr int MAX_ITER = 2;
constexpr int CHECK_TERMINATION = 1;
constexpr tinytype STALL_TORQUE = 0.023625177104190306;
constexpr tinytype FREE_SPEED = 2251.4747350726848;
constexpr tinytype SATURATION_TORQUE = 0.014999999999999999;
constexpr tinytype INPUT_BOUND_LIMIT = 1000000000;
constexpr int WHEEL_START = 2;
constexpr int TORQUE_START = 3;

constexpr tinytype STATE_SCALE[4] = {1, 1, 2251.4747350726848, 0.014999999999999999};
constexpr tinytype INPUT_SCALE[1] = {0.75};
constexpr tinytype INITIAL_STATE[4] = {0, 0, 0, 0};
constexpr tinytype A_DYN[4][4] = {
    1.0205429964793766, 0.020136766659434775, 0, -0.0034901455112770438,
    2.0613044966510112, 1.0205429964793766, 0, -0.35020463755538739,
    -0.00091553525542204602, -9.1242402854294145e-06, 1, 0.014960655541089741,
    -2.2607178930419993e-15, -2.1892401735740146e-17, 0, 0.99999999999999956
};
constexpr tinytype B_DYN[4][1] = {
    -0.001161796291494867,
    -0.17450727556385226,
    0.007480063480120213,
    1.0000000000000004
};
constexpr tinytype Q_DIAG[4] = {1000, 10, 9.9999999999999995e-07, 1};
constexpr tinytype R_DIAG[1] = {1};

}  // namespace mpc_config
