[platformio]
default_envs = esp32s3

[env:esp32s3]
platform = espressif32
board = adafruit_qtpy_esp32s3_n4r2
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.flash_size = 4MB
board_build.partitions = default.csv
board_build.flash_mode = dio
board_build.f_flash = 80000000L
board_build.arduino.memory_type = dio_qspi
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
upload_protocol = esptool
upload_resetmethod = usb_serial_jtag
build_type = release
lib_ldf_mode = deep+
build_src_filter =
    +<*>
    -<boot_probe.cpp>
build_unflags =
    -Os
    -std=gnu++11
build_flags =
    -O3
    -std=gnu++17
    -mtext-section-literals
    -fno-var-tracking-assignments
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_DFU_ON_BOOT=0
    -D CORE_DEBUG_LEVEL=3
    -D EIGEN_NO_DEBUG
    -D EIGEN_DONT_VECTORIZE
    -D EIGEN_MPL2_ONLY
    -I lib/TinyMPC/src
    -I lib/TinyMPC/src/include/Eigen

[env:test]
extends = env:esp32s3
build_src_filter =
    -<*>
    +<test.cpp>
